baseURL: 'https://dotpwsh.com/'
languageCode: en-us
title: .pwsh
theme: dotpwsh
PygmentsCodeFences: true
PygmentsUseClasses: true
PygmentsStyle: fruity
markup:
  highlight:
    tabWidth: 4
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
params:
  OwnerName: Mads Moi-Aune
  Twitter: dotpwsh
  Github: dotpwsh
  Reddit: dotpwsh
permalinks:
  posts: '/:year/:month/:day/:filename/'
